apps/authentication/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin

from apps import db, login_manager

from apps.authentication.util import hash_pass

class Users(db.Model, UserMixin):

    __tablename__ = 'Users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True)
    email = db.Column(db.String(64), unique=True)
    password = db.Column(db.LargeBinary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass(value)  # we need bytes here (not plain str)

            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return Users.query.filter_by(id=id).first()


@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = Users.query.filter_by(username=username).first()
    return user if user else None

apps/authentication/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import Email, DataRequired

# login and registration


class LoginForm(FlaskForm):
    username = StringField('Username',
                         id='username_login',
                         validators=[DataRequired()])
    password = PasswordField('Password',
                             id='pwd_login',
                             validators=[DataRequired()])


class CreateAccountForm(FlaskForm):
    username = StringField('Username',
                         id='username_create',
                         validators=[DataRequired()])
    email = StringField('Email',
                      id='email_create',
                      validators=[DataRequired(), Email()])
    password = PasswordField('Password',
                             id='pwd_create',
                             validators=[DataRequired()])

apps/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from importlib import import_module


db = SQLAlchemy()
login_manager = LoginManager()


def register_extensions(app):
    db.init_app(app)
    login_manager.init_app(app)


def register_blueprints(app):
    for module_name in ('authentication', 'home'):
        module = import_module('apps.{}.routes'.format(module_name))
        app.register_blueprint(module.blueprint)


def configure_database(app):

    @app.before_first_request
    def initialize_database():
        db.create_all()

    @app.teardown_request
    def shutdown_session(exception=None):
        db.session.remove()


def create_app(config):
    app = Flask(__name__)
    app.config.from_object(config)
    register_extensions(app)
    register_blueprints(app)
    configure_database(app)
    return app

apps/authentication/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'authentication_blueprint',
    __name__,
    url_prefix=''
)

apps/authentication/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_user,
    logout_user
)

from apps import db, login_manager
from apps.authentication import blueprint
from apps.authentication.forms import LoginForm, CreateAccountForm
from apps.authentication.models import Users

from apps.authentication.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('authentication_blueprint.login'))

# Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:

        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = Users.query.filter_by(username=username).first()

        # Check the password
        if user and verify_pass(password, user.password):

            login_user(user)
            return redirect(url_for('authentication_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template('accounts/login.html',
                               msg='Wrong user or password',
                               form=login_form)

    if not current_user.is_authenticated:
        return render_template('accounts/login.html',
                               form=login_form)
    return redirect(url_for('home_blueprint.index'))


@blueprint.route('/register', methods=['GET', 'POST'])
def register():
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username = request.form['username']
        email = request.form['email']

        # Check usename exists
        user = Users.query.filter_by(username=username).first()
        if user:
            return render_template('accounts/register.html',
                                   msg='Username already registered',
                                   success=False,
                                   form=create_account_form)

        # Check email exists
        user = Users.query.filter_by(email=email).first()
        if user:
            return render_template('accounts/register.html',
                                   msg='Email already registered',
                                   success=False,
                                   form=create_account_form)

        # else we can create the user
        user = Users(**request.form)
        db.session.add(user)
        db.session.commit()

        # Delete user from session
        logout_user()

        return render_template('accounts/register.html',
                               msg='User created successfully.',
                               success=True,
                               form=create_account_form)

    else:
        return render_template('accounts/register.html', form=create_account_form)


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('authentication_blueprint.login')) 

# Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('home/page-403.html'), 403


@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('home/page-403.html'), 403


@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('home/page-404.html'), 404


@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('home/page-500.html'), 500

apps/home/__init__.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'home_blueprint',
    __name__,
    url_prefix=''
)

apps/home/routes.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from apps.home import blueprint
from flask import render_template, request
from flask_login import login_required
from jinja2 import TemplateNotFound


@blueprint.route('/index')
@login_required
def index():

    return render_template('home/index.html', segment='index')


@blueprint.route('/<template>')
@login_required
def route_template(template):

    try:

        if not template.endswith('.html'):
            template += '.html'

        # Detect the current page
        segment = get_segment(request)

        # Serve the file (if exists) from app/templates/home/FILE.html
        return render_template("home/" + template, segment=segment)

    except TemplateNotFound:
        return render_template('home/page-404.html'), 404

    except:
        return render_template('home/page-500.html'), 500


# Helper - Extract current page name from request
def get_segment(request):

    try:

        segment = request.path.split('/')[-1]

        if segment == '':
            segment = 'index'

        return segment

    except:
        return None

apps/templates/accounts/login.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Login</h4>
                            <br />
                            <p>
                                {% if msg %}
                                    {{ msg | safe }}
                                {% else %}
                                    Add your credentials
                                {% endif %}
                            </p>
                        </div>
                        <div class="card-body">

                            <form role="form" method="post" action="">

                                {{ form.hidden_tag() }}

                                <div class="row">

                                    <div class="col-md-1 px-1">
                                        <div class="form-group">
                                            <label>Username</label>
                                        </div>
                                    </div>

                                    <div class="col-md-5 px-1">
                                        <div class="form-group">
                                            {{ form.username(placeholder="Username", class="form-control") }}
                                        </div>
                                    </div>

                                </div>
                                <div class="row">

                                    <div class="col-md-1 pl-1">
                                        <div class="form-group">
                                            <label>Password</label>
                                        </div>
                                    </div>

                                    <div class="col-md-5 pl-1">
                                        <div class="form-group">
                                            {{ form.password(placeholder="Password", class="form-control", type="password") }}
                                        </div>
                                    </div>

                                </div>

                                <div class="row">
                                    <div class="col-md-1 pl-1"></div>

                                    <div class="col-md-5 pl-1">
                                        <button name="login" type="submit" class="btn btn-info btn-fill">Login</button>

                                        &nbsp; &nbsp; Don't have an account? <a href="{{ url_for('authentication_blueprint.register') }}" >Register</a>
                                        <div class="clearfix"></div>                                        
                                    </div>

                                </div>

                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/accounts/register.html
{% extends "layouts/base.html" %}

{% block title %} Register {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Register</h4>
                            <br />
                            <p>
                                {% if msg %}
                                    {{ msg | safe }}
                                {% else %}
                                    Add your credentials
                                {% endif %}
                            </p>
                        </div>
                        <div class="card-body">

                            <form role="form" method="post" action="">

                                {{ form.hidden_tag() }} 
                                
                                <div class="row">

                                    <div class="col-md-1 px-1">
                                        <div class="form-group">
                                            <label>Username</label>
                                        </div>
                                    </div>

                                    <div class="col-md-5 px-1">
                                        <div class="form-group">
                                            {{ form.username(placeholder="Username", class="form-control") }}
                                        </div>
                                    </div>

                                </div>

                                <div class="row">

                                    <div class="col-md-1 px-1">
                                        <div class="form-group">
                                            <label>eMail</label>
                                        </div>
                                    </div>

                                    <div class="col-md-5 px-1">
                                        <div class="form-group">
                                            {{ form.email(placeholder="Email", class="input form-control", type="email") }}
                                        </div>
                                    </div>

                                </div>

                                <div class="row">

                                    <div class="col-md-1 pl-1">
                                        <div class="form-group">
                                            <label>Password</label>
                                        </div>
                                    </div>

                                    <div class="col-md-5 pl-1">
                                        <div class="form-group">
                                            {{ form.password(placeholder="Password", class="form-control", type="password") }}
                                        </div>
                                    </div>

                                </div>

                                <div class="row">
                                    <div class="col-md-1 pl-1"></div>

                                    <div class="col-md-5 pl-1">
                                        <button name="register" type="submit" class="btn btn-info btn-fill">Register</button>

                                        &nbsp; &nbsp; Have an account? <a href="{{ url_for('authentication_blueprint.login') }}" >Login</a>
                                        <div class="clearfix"></div>                                        
                                    </div>

                                </div>

                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/login.html
{% extends "layouts/base.html" %}

{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">

        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">Login</h4>
                            Add your credentials
                        </div>

                        <br />
                        <div class="card-body">

                            <form method="" action="/">

                                <div class="row">

                                    <div class="col-md-1 px-1">
                                        <div class="form-group">
                                            <label>Username</label>
                                        </div>
                                    </div>

                                    <div class="col-md-5 px-1">
                                        <div class="form-group">
                                            <input type="text" class="form-control" placeholder="Username" value="">
                                        </div>
                                    </div>

                                </div>
                                <div class="row">

                                    <div class="col-md-1 pl-1">
                                        <div class="form-group">
                                            <label>Password</label>
                                        </div>
                                    </div>

                                    <div class="col-md-5 pl-1">
                                        <div class="form-group">
                                            <input type="password" class="form-control" placeholder="Password" value="">
                                        </div>
                                    </div>

                                </div>

                                <div class="row">
                                    <div class="col-md-1 pl-1"></div>

                                    <div class="col-md-5 pl-1">
                                        <button name="login" type="submit" class="btn btn-info btn-fill">Login</button>

                                        &nbsp; &nbsp; Don't have an account? <a href="/register.html" >Register</a>
                                        <div class="clearfix"></div>                                        
                                    </div>

                                </div>

                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/maps.html
{% extends "layouts/base.html" %}

{% block title %} Google Maps {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="map-container">
        <div id="map"></div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<!--  Google Maps Plugin    -->
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
<script type="text/javascript">
    $(document).ready(function() {
        // Javascript method's body can be found in assets/js/demos.js
        demo.initGoogleMaps();

    });
</script>

{% endblock javascripts %}

apps/templates/home/page-403.html
{% extends "layouts/base.html" %}

{% block title %} 403 Error {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">
                                Error 403 - Access Denied.
                            </h4>
                            <br />
                            <p>
                                Please contact support or <a href="/login.html" class="btn btn-info btn-fill">Authenticate</a>. 
                            </p>
                            <br />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-404.html
{% extends "layouts/base.html" %}

{% block title %} 404 Error {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">
                                Error 404 - Page not found.
                            </h4>
                            <br />
                            <p>
                                Please contact support or access the <a href="/" class="btn btn-info btn-fill">HOME</a> page. 
                            </p>
                            <br />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/home/page-500.html
{% extends "layouts/base.html" %}

{% block title %} 500 Error {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <h4 class="card-title">
                                Error 500 - Server Error.
                            </h4>
                            <br />
                            <p>
                                Please contact support or access the <a href="/" class="btn btn-info btn-fill">HOME</a> page. 
                            </p>
                            <br />
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/includes/navigation.html
            <!-- Navbar -->
            <nav class="navbar navbar-expand-lg " color-on-scroll="500">
                <div class="container-fluid">
                    <a class="navbar-brand" href="#pablo"> Dashboard </a>
                    <button href="" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                        <span class="navbar-toggler-bar burger-lines"></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navigation">
                        {% if current_user.is_authenticated %}
                        <ul class="nav navbar-nav mr-auto">
                            <li class="nav-item">
                                <a href="#" class="nav-link" data-toggle="dropdown">
                                    <i class="nc-icon nc-palette"></i>
                                    <span class="d-lg-none">Dashboard</span>
                                </a>
                            </li>
                            <li class="dropdown nav-item">
                                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                                    <i class="nc-icon nc-planet"></i>
                                    <span class="notification">5</span>
                                    <span class="d-lg-none">Notification</span>
                                </a>
                                <ul class="dropdown-menu">
                                    <a class="dropdown-item" href="#">Notification 1</a>
                                    <a class="dropdown-item" href="#">Notification 2</a>
                                    <a class="dropdown-item" href="#">Notification 3</a>
                                    <a class="dropdown-item" href="#">Notification 4</a>
                                    <a class="dropdown-item" href="#">Another notification</a>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="nc-icon nc-zoom-split"></i>
                                    <span class="d-lg-block">&nbsp;Search</span>
                                </a>
                            </li>
                        </ul>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="/user.html">
                                    <span class="no-icon">Account</span>
                                </a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" 
                                   href="https://appseed.us" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <span class="no-icon">Dropdown</span>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <a class="dropdown-item" href="#">Something</a>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                    <div class="divider"></div>
                                    <a class="dropdown-item" href="#">Separated link</a>
                                </div>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ url_for('authentication_blueprint.logout') }}">
                                    <span class="no-icon">Log out</span>
                                </a>
                            </li>
                        </ul>
                        {% endif %}
                    </div>
                </div>
            </nav>

apps/templates/includes/sidebar.html
<div class="sidebar" data-image="/static/assets/img/sidebar-5.jpg">
    <!--
Tip 1: You can change the color of the sidebar using: data-color="purple | blue | green | orange | red"

Tip 2: you can also add an image using data-image tag
-->
    <div class="sidebar-wrapper">
        <div class="logo">
            <a href="/" class="simple-text">
                Flask Light
            </a>
        </div>
        <ul class="nav">
            {% if current_user.is_authenticated %}
            <li class="nav-item nav-item {% if 'index' in segment %} active {% endif %}">
                <a class="nav-link" href="/">
                    <i class="nc-icon nc-chart-pie-35"></i>
                    <p>Dashboard</p>
                </a>
            </li>
            <li class="nav-item nav-item {% if 'user' in segment %} active {% endif %}">
                <a class="nav-link" href="/user.html">
                    <i class="nc-icon nc-circle-09"></i>
                    <p>User Profile</p>
                </a>
            </li>
            <li class="nav-item nav-item {% if 'table' in segment %} active {% endif %}">
                <a class="nav-link" href="/table.html">
                    <i class="nc-icon nc-notes"></i>
                    <p>Table List</p>
                </a>
            </li>
            <li class="nav-item nav-item {% if 'typography' in segment %} active {% endif %}">
                <a class="nav-link" href="/typography.html">
                    <i class="nc-icon nc-paper-2"></i>
                    <p>Typography</p>
                </a>
            </li>
            <li class="nav-item nav-item {% if 'icons' in segment %} active {% endif %}">
                <a class="nav-link" href="/icons.html">
                    <i class="nc-icon nc-atom"></i>
                    <p>Icons</p>
                </a>
            </li>
            <li class="nav-item nav-item {% if 'maps' in segment %} active {% endif %}">
                <a class="nav-link" href="/maps.html">
                    <i class="nc-icon nc-pin-3"></i>
                    <p>Maps</p>
                </a>
            </li>
            <li class="nav-item nav-item {% if 'notif' in segment %} active {% endif %}">
                <a class="nav-link" href="/notifications.html">
                    <i class="nc-icon nc-bell-55"></i>
                    <p>Notifications</p>
                </a>
            </li>
            <li class="nav-item nav-item {% if '404' in segment %} active {% endif %}">
                <a class="nav-link" href="/page-404.html">
                    <i class="nc-icon nc-settings-gear-64"></i>
                    <p>Error 404</p>
                </a>
            </li>
            <li>
                <a class="nav-link" href="{{ url_for('authentication_blueprint.logout') }}">
                    <i class="nc-icon nc-button-power"></i>
                    <p>Logout</p>
                </a>
            </li>
            
            <li class="nav-item active active-pro">
                <a class="nav-link active" target="_blank" 
                   href="https://appseed.us/admin-dashboards/flask-dashboard-material-pro">
                    <i class="nc-icon nc-spaceship"></i>
                    <p>PRO Version</p>
                </a>
            </li>
            {% else %}
            <li class="nav-item active">
                <a class="nav-link active" target="_blank" 
                   href="https://appseed.us/admin-dashboards/flask-dashboard-material-pro">
                    <i class="nc-icon nc-spaceship"></i>
                    <p>PRO Version</p>
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</div>